bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.001_F.fastq.gz | samtools sort -o mbp/map/27.001_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.001_M.fastq.gz | samtools sort -o mbp/map/27.001_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.002_F.fastq.gz | samtools sort -o mbp/map/27.002_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.002_M.fastq.gz | samtools sort -o mbp/map/27.002_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.003_F.fastq.gz | samtools sort -o mbp/map/27.003_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.003_M.fastq.gz | samtools sort -o mbp/map/27.003_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.004_F.fastq.gz | samtools sort -o mbp/map/27.004_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.004_M.fastq.gz | samtools sort -o mbp/map/27.004_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.005_F.fastq.gz | samtools sort -o mbp/map/27.005_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.005_M.fastq.gz | samtools sort -o mbp/map/27.005_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.009_F.fastq.gz | samtools sort -o mbp/map/27.009_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.009_M.fastq.gz | samtools sort -o mbp/map/27.009_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.01_F.fastq.gz | samtools sort -o mbp/map/27.01_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.01_M.fastq.gz | samtools sort -o mbp/map/27.01_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.011_F.fastq.gz | samtools sort -o mbp/map/27.011_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.011_M.fastq.gz | samtools sort -o mbp/map/27.011_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.012_F.fastq.gz | samtools sort -o mbp/map/27.012_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.012_M.fastq.gz | samtools sort -o mbp/map/27.012_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.013_F.fastq.gz | samtools sort -o mbp/map/27.013_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.013_M.fastq.gz | samtools sort -o mbp/map/27.013_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.014_F.fastq.gz | samtools sort -o mbp/map/27.014_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.014_M.fastq.gz | samtools sort -o mbp/map/27.014_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.015_F.fastq.gz | samtools sort -o mbp/map/27.015_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.015_M.fastq.gz | samtools sort -o mbp/map/27.015_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.016_F.fastq.gz | samtools sort -o mbp/map/27.016_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.016_M.fastq.gz | samtools sort -o mbp/map/27.016_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.017_F.fastq.gz | samtools sort -o mbp/map/27.017_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.017_M.fastq.gz | samtools sort -o mbp/map/27.017_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.019_F.fastq.gz | samtools sort -o mbp/map/27.019_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.019_M.fastq.gz | samtools sort -o mbp/map/27.019_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.02_F.fastq.gz | samtools sort -o mbp/map/27.02_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.02_M.fastq.gz | samtools sort -o mbp/map/27.02_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.021_F.fastq.gz | samtools sort -o mbp/map/27.021_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.021_M.fastq.gz | samtools sort -o mbp/map/27.021_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.022_F.fastq.gz | samtools sort -o mbp/map/27.022_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.022_M.fastq.gz | samtools sort -o mbp/map/27.022_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.023_F.fastq.gz | samtools sort -o mbp/map/27.023_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.023_M.fastq.gz | samtools sort -o mbp/map/27.023_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.025_F.fastq.gz | samtools sort -o mbp/map/27.025_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.025_M.fastq.gz | samtools sort -o mbp/map/27.025_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.026_F.fastq.gz | samtools sort -o mbp/map/27.026_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.026_M.fastq.gz | samtools sort -o mbp/map/27.026_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.027_F.fastq.gz | samtools sort -o mbp/map/27.027_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.027_M.fastq.gz | samtools sort -o mbp/map/27.027_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.028_F.fastq.gz | samtools sort -o mbp/map/27.028_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.028_M.fastq.gz | samtools sort -o mbp/map/27.028_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.029_F.fastq.gz | samtools sort -o mbp/map/27.029_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.029_M.fastq.gz | samtools sort -o mbp/map/27.029_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.031_F.fastq.gz | samtools sort -o mbp/map/27.031_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.031_M.fastq.gz | samtools sort -o mbp/map/27.031_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.032_F.fastq.gz | samtools sort -o mbp/map/27.032_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.032_M.fastq.gz | samtools sort -o mbp/map/27.032_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.033_F.fastq.gz | samtools sort -o mbp/map/27.033_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.033_M.fastq.gz | samtools sort -o mbp/map/27.033_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.034_F.fastq.gz | samtools sort -o mbp/map/27.034_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.034_M.fastq.gz | samtools sort -o mbp/map/27.034_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.035_F.fastq.gz | samtools sort -o mbp/map/27.035_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.035_M.fastq.gz | samtools sort -o mbp/map/27.035_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.036_F.fastq.gz | samtools sort -o mbp/map/27.036_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.036_M.fastq.gz | samtools sort -o mbp/map/27.036_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.037_F.fastq.gz | samtools sort -o mbp/map/27.037_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.037_M.fastq.gz | samtools sort -o mbp/map/27.037_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.038_F.fastq.gz | samtools sort -o mbp/map/27.038_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.038_M.fastq.gz | samtools sort -o mbp/map/27.038_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.039_F.fastq.gz | samtools sort -o mbp/map/27.039_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.039_M.fastq.gz | samtools sort -o mbp/map/27.039_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.04_F.fastq.gz | samtools sort -o mbp/map/27.04_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.04_M.fastq.gz | samtools sort -o mbp/map/27.04_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.041_F.fastq.gz | samtools sort -o mbp/map/27.041_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.041_M.fastq.gz | samtools sort -o mbp/map/27.041_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.042_F.fastq.gz | samtools sort -o mbp/map/27.042_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.042_M.fastq.gz | samtools sort -o mbp/map/27.042_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.043_F.fastq.gz | samtools sort -o mbp/map/27.043_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.043_M.fastq.gz | samtools sort -o mbp/map/27.043_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.044_F.fastq.gz | samtools sort -o mbp/map/27.044_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.044_M.fastq.gz | samtools sort -o mbp/map/27.044_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.045_F.fastq.gz | samtools sort -o mbp/map/27.045_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.045_M.fastq.gz | samtools sort -o mbp/map/27.045_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.046_F.fastq.gz | samtools sort -o mbp/map/27.046_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.046_M.fastq.gz | samtools sort -o mbp/map/27.046_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.047_F.fastq.gz | samtools sort -o mbp/map/27.047_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.047_M.fastq.gz | samtools sort -o mbp/map/27.047_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.048_F.fastq.gz | samtools sort -o mbp/map/27.048_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.048_M.fastq.gz | samtools sort -o mbp/map/27.048_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.05_F.fastq.gz | samtools sort -o mbp/map/27.05_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.05_M.fastq.gz | samtools sort -o mbp/map/27.05_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.051_F.fastq.gz | samtools sort -o mbp/map/27.051_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.051_M.fastq.gz | samtools sort -o mbp/map/27.051_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.052_F.fastq.gz | samtools sort -o mbp/map/27.052_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.052_M.fastq.gz | samtools sort -o mbp/map/27.052_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.053_F.fastq.gz | samtools sort -o mbp/map/27.053_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.053_M.fastq.gz | samtools sort -o mbp/map/27.053_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.054_F.fastq.gz | samtools sort -o mbp/map/27.054_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.054_M.fastq.gz | samtools sort -o mbp/map/27.054_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.056_F.fastq.gz | samtools sort -o mbp/map/27.056_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.056_M.fastq.gz | samtools sort -o mbp/map/27.056_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.057_F.fastq.gz | samtools sort -o mbp/map/27.057_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.057_M.fastq.gz | samtools sort -o mbp/map/27.057_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.058_F.fastq.gz | samtools sort -o mbp/map/27.058_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.058_M.fastq.gz | samtools sort -o mbp/map/27.058_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.059_F.fastq.gz | samtools sort -o mbp/map/27.059_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.059_M.fastq.gz | samtools sort -o mbp/map/27.059_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.06_F.fastq.gz | samtools sort -o mbp/map/27.06_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.06_M.fastq.gz | samtools sort -o mbp/map/27.06_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.061_F.fastq.gz | samtools sort -o mbp/map/27.061_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.061_M.fastq.gz | samtools sort -o mbp/map/27.061_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.062_F.fastq.gz | samtools sort -o mbp/map/27.062_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.062_M.fastq.gz | samtools sort -o mbp/map/27.062_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.063_F.fastq.gz | samtools sort -o mbp/map/27.063_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.063_M.fastq.gz | samtools sort -o mbp/map/27.063_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.064_F.fastq.gz | samtools sort -o mbp/map/27.064_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.064_M.fastq.gz | samtools sort -o mbp/map/27.064_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.066_F.fastq.gz | samtools sort -o mbp/map/27.066_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.066_M.fastq.gz | samtools sort -o mbp/map/27.066_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.067_F.fastq.gz | samtools sort -o mbp/map/27.067_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.067_M.fastq.gz | samtools sort -o mbp/map/27.067_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.07_F.fastq.gz | samtools sort -o mbp/map/27.07_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.07_M.fastq.gz | samtools sort -o mbp/map/27.07_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.071_F.fastq.gz | samtools sort -o mbp/map/27.071_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.071_M.fastq.gz | samtools sort -o mbp/map/27.071_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.072_F.fastq.gz | samtools sort -o mbp/map/27.072_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.072_M.fastq.gz | samtools sort -o mbp/map/27.072_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.073_F.fastq.gz | samtools sort -o mbp/map/27.073_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.073_M.fastq.gz | samtools sort -o mbp/map/27.073_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.074_F.fastq.gz | samtools sort -o mbp/map/27.074_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.074_M.fastq.gz | samtools sort -o mbp/map/27.074_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.075_F.fastq.gz | samtools sort -o mbp/map/27.075_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.075_M.fastq.gz | samtools sort -o mbp/map/27.075_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.078_F.fastq.gz | samtools sort -o mbp/map/27.078_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.078_M.fastq.gz | samtools sort -o mbp/map/27.078_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.081_F.fastq.gz | samtools sort -o mbp/map/27.081_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/27.081_M.fastq.gz | samtools sort -o mbp/map/27.081_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.001_F.fastq.gz | samtools sort -o mbp/map/29.001_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.001_M.fastq.gz | samtools sort -o mbp/map/29.001_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.002_F.fastq.gz | samtools sort -o mbp/map/29.002_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.002_M.fastq.gz | samtools sort -o mbp/map/29.002_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.003_F.fastq.gz | samtools sort -o mbp/map/29.003_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.003_M.fastq.gz | samtools sort -o mbp/map/29.003_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.004_F.fastq.gz | samtools sort -o mbp/map/29.004_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.004_M.fastq.gz | samtools sort -o mbp/map/29.004_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.006_F.fastq.gz | samtools sort -o mbp/map/29.006_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.006_M.fastq.gz | samtools sort -o mbp/map/29.006_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.007_F.fastq.gz | samtools sort -o mbp/map/29.007_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.007_M.fastq.gz | samtools sort -o mbp/map/29.007_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.009_F.fastq.gz | samtools sort -o mbp/map/29.009_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.009_M.fastq.gz | samtools sort -o mbp/map/29.009_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.01_F.fastq.gz | samtools sort -o mbp/map/29.01_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.01_M.fastq.gz | samtools sort -o mbp/map/29.01_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.011_F.fastq.gz | samtools sort -o mbp/map/29.011_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.011_M.fastq.gz | samtools sort -o mbp/map/29.011_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.012_F.fastq.gz | samtools sort -o mbp/map/29.012_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.012_M.fastq.gz | samtools sort -o mbp/map/29.012_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.013_F.fastq.gz | samtools sort -o mbp/map/29.013_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.013_M.fastq.gz | samtools sort -o mbp/map/29.013_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.014_F.fastq.gz | samtools sort -o mbp/map/29.014_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.014_M.fastq.gz | samtools sort -o mbp/map/29.014_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.015_F.fastq.gz | samtools sort -o mbp/map/29.015_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.015_M.fastq.gz | samtools sort -o mbp/map/29.015_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.016_F.fastq.gz | samtools sort -o mbp/map/29.016_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.016_M.fastq.gz | samtools sort -o mbp/map/29.016_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.017_F.fastq.gz | samtools sort -o mbp/map/29.017_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.017_M.fastq.gz | samtools sort -o mbp/map/29.017_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.018_F.fastq.gz | samtools sort -o mbp/map/29.018_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.018_M.fastq.gz | samtools sort -o mbp/map/29.018_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.02_F.fastq.gz | samtools sort -o mbp/map/29.02_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.02_M.fastq.gz | samtools sort -o mbp/map/29.02_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.022_F.fastq.gz | samtools sort -o mbp/map/29.022_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.022_M.fastq.gz | samtools sort -o mbp/map/29.022_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.023_F.fastq.gz | samtools sort -o mbp/map/29.023_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.023_M.fastq.gz | samtools sort -o mbp/map/29.023_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.024_F.fastq.gz | samtools sort -o mbp/map/29.024_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.024_M.fastq.gz | samtools sort -o mbp/map/29.024_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.025_F.fastq.gz | samtools sort -o mbp/map/29.025_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.025_M.fastq.gz | samtools sort -o mbp/map/29.025_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.026_F.fastq.gz | samtools sort -o mbp/map/29.026_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.026_M.fastq.gz | samtools sort -o mbp/map/29.026_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.027_F.fastq.gz | samtools sort -o mbp/map/29.027_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.027_M.fastq.gz | samtools sort -o mbp/map/29.027_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.029_F.fastq.gz | samtools sort -o mbp/map/29.029_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.029_M.fastq.gz | samtools sort -o mbp/map/29.029_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.03_F.fastq.gz | samtools sort -o mbp/map/29.03_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.03_M.fastq.gz | samtools sort -o mbp/map/29.03_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.031_F.fastq.gz | samtools sort -o mbp/map/29.031_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.031_M.fastq.gz | samtools sort -o mbp/map/29.031_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.032_F.fastq.gz | samtools sort -o mbp/map/29.032_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.032_M.fastq.gz | samtools sort -o mbp/map/29.032_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.033_F.fastq.gz | samtools sort -o mbp/map/29.033_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.033_M.fastq.gz | samtools sort -o mbp/map/29.033_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.034_F.fastq.gz | samtools sort -o mbp/map/29.034_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.034_M.fastq.gz | samtools sort -o mbp/map/29.034_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.035_F.fastq.gz | samtools sort -o mbp/map/29.035_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.035_M.fastq.gz | samtools sort -o mbp/map/29.035_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.036_F.fastq.gz | samtools sort -o mbp/map/29.036_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.036_M.fastq.gz | samtools sort -o mbp/map/29.036_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.037_F.fastq.gz | samtools sort -o mbp/map/29.037_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.037_M.fastq.gz | samtools sort -o mbp/map/29.037_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.038_F.fastq.gz | samtools sort -o mbp/map/29.038_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.038_M.fastq.gz | samtools sort -o mbp/map/29.038_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.039_F.fastq.gz | samtools sort -o mbp/map/29.039_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.039_M.fastq.gz | samtools sort -o mbp/map/29.039_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.04_F.fastq.gz | samtools sort -o mbp/map/29.04_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.04_M.fastq.gz | samtools sort -o mbp/map/29.04_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.042_F.fastq.gz | samtools sort -o mbp/map/29.042_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.042_M.fastq.gz | samtools sort -o mbp/map/29.042_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.044_F.fastq.gz | samtools sort -o mbp/map/29.044_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.044_M.fastq.gz | samtools sort -o mbp/map/29.044_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.045_F.fastq.gz | samtools sort -o mbp/map/29.045_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.045_M.fastq.gz | samtools sort -o mbp/map/29.045_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.047_F.fastq.gz | samtools sort -o mbp/map/29.047_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.047_M.fastq.gz | samtools sort -o mbp/map/29.047_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.048_F.fastq.gz | samtools sort -o mbp/map/29.048_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.048_M.fastq.gz | samtools sort -o mbp/map/29.048_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.049_F.fastq.gz | samtools sort -o mbp/map/29.049_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.049_M.fastq.gz | samtools sort -o mbp/map/29.049_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.05_F.fastq.gz | samtools sort -o mbp/map/29.05_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.05_M.fastq.gz | samtools sort -o mbp/map/29.05_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.051_F.fastq.gz | samtools sort -o mbp/map/29.051_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.051_M.fastq.gz | samtools sort -o mbp/map/29.051_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.052_F.fastq.gz | samtools sort -o mbp/map/29.052_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.052_M.fastq.gz | samtools sort -o mbp/map/29.052_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.053_F.fastq.gz | samtools sort -o mbp/map/29.053_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.053_M.fastq.gz | samtools sort -o mbp/map/29.053_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.054_F.fastq.gz | samtools sort -o mbp/map/29.054_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.054_M.fastq.gz | samtools sort -o mbp/map/29.054_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.055_F.fastq.gz | samtools sort -o mbp/map/29.055_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.055_M.fastq.gz | samtools sort -o mbp/map/29.055_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.057_F.fastq.gz | samtools sort -o mbp/map/29.057_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.057_M.fastq.gz | samtools sort -o mbp/map/29.057_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.058_F.fastq.gz | samtools sort -o mbp/map/29.058_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.058_M.fastq.gz | samtools sort -o mbp/map/29.058_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.059_F.fastq.gz | samtools sort -o mbp/map/29.059_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.059_M.fastq.gz | samtools sort -o mbp/map/29.059_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.06_F.fastq.gz | samtools sort -o mbp/map/29.06_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.06_M.fastq.gz | samtools sort -o mbp/map/29.06_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.062_F.fastq.gz | samtools sort -o mbp/map/29.062_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.062_M.fastq.gz | samtools sort -o mbp/map/29.062_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.063_F.fastq.gz | samtools sort -o mbp/map/29.063_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.063_M.fastq.gz | samtools sort -o mbp/map/29.063_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.065_F.fastq.gz | samtools sort -o mbp/map/29.065_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.065_M.fastq.gz | samtools sort -o mbp/map/29.065_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.067_F.fastq.gz | samtools sort -o mbp/map/29.067_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.067_M.fastq.gz | samtools sort -o mbp/map/29.067_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.068_F.fastq.gz | samtools sort -o mbp/map/29.068_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.068_M.fastq.gz | samtools sort -o mbp/map/29.068_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.07_F.fastq.gz | samtools sort -o mbp/map/29.07_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.07_M.fastq.gz | samtools sort -o mbp/map/29.07_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.072_F.fastq.gz | samtools sort -o mbp/map/29.072_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.072_M.fastq.gz | samtools sort -o mbp/map/29.072_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.073_F.fastq.gz | samtools sort -o mbp/map/29.073_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.073_M.fastq.gz | samtools sort -o mbp/map/29.073_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.074_F.fastq.gz | samtools sort -o mbp/map/29.074_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.074_M.fastq.gz | samtools sort -o mbp/map/29.074_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.075_F.fastq.gz | samtools sort -o mbp/map/29.075_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.075_M.fastq.gz | samtools sort -o mbp/map/29.075_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.076_F.fastq.gz | samtools sort -o mbp/map/29.076_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.076_M.fastq.gz | samtools sort -o mbp/map/29.076_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.077_F.fastq.gz | samtools sort -o mbp/map/29.077_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.077_M.fastq.gz | samtools sort -o mbp/map/29.077_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.079_F.fastq.gz | samtools sort -o mbp/map/29.079_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.079_M.fastq.gz | samtools sort -o mbp/map/29.079_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.08_F.fastq.gz | samtools sort -o mbp/map/29.08_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.08_M.fastq.gz | samtools sort -o mbp/map/29.08_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.083_F.fastq.gz | samtools sort -o mbp/map/29.083_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.083_M.fastq.gz | samtools sort -o mbp/map/29.083_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.084_F.fastq.gz | samtools sort -o mbp/map/29.084_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.084_M.fastq.gz | samtools sort -o mbp/map/29.084_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.085_F.fastq.gz | samtools sort -o mbp/map/29.085_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.085_M.fastq.gz | samtools sort -o mbp/map/29.085_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.086_F.fastq.gz | samtools sort -o mbp/map/29.086_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.086_M.fastq.gz | samtools sort -o mbp/map/29.086_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.087_F.fastq.gz | samtools sort -o mbp/map/29.087_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.087_M.fastq.gz | samtools sort -o mbp/map/29.087_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.088_F.fastq.gz | samtools sort -o mbp/map/29.088_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.088_M.fastq.gz | samtools sort -o mbp/map/29.088_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.094_F.fastq.gz | samtools sort -o mbp/map/29.094_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.094_M.fastq.gz | samtools sort -o mbp/map/29.094_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.095_F.fastq.gz | samtools sort -o mbp/map/29.095_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.095_M.fastq.gz | samtools sort -o mbp/map/29.095_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.096_F.fastq.gz | samtools sort -o mbp/map/29.096_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.096_M.fastq.gz | samtools sort -o mbp/map/29.096_M.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.097_F.fastq.gz | samtools sort -o mbp/map/29.097_F.bam
bwa mem -M Cgigas_RefSeq.fasta mbp/trim/29.097_M.fastq.gz | samtools sort -o mbp/map/29.097_M.bam
